name: Organization Activity Graph

on:
  schedule:
    - cron: '0 0 * * *'  # каждый день в полночь
  workflow_dispatch:     # чтобы запускать вручную

jobs:
  generate-org-graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate metrics for organization
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: 6-eyes-game-studios
          base: ""
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_limit: 10
          plugin_activity_filter: issue,pr,release,fork,review,commit
          plugin_activity_timestamps: yes
          plugin_activity_topics: yes
          output_action: inline
          filename: activity-graph.svg
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add activity-graph.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update activity graph"
          git push
